CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_name TEXT NOT NULL, 
    user_number TEXT NOT NULL, 
    user_email TEXT, 
    user_street TEXT, 
    user_city TEXT, 
    user_state TEXT, 
    user_zip INTEGER
);