CREATE TABLE cart (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) NOT NULL, 
    treatment_id INTEGER REFERENCES treatments(id) ON DELETE CASCADE, 
    comment TEXT, 
    order_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    appointment_date TIMESTAMPTZ NOT NULL
);